create table EMPLOYEETB
(
EMPID INT IDENTITY(1,1) NOT NULL,
FIRSTNAME VARCHAR(75) NOT NULL,
LASTNAME VARCHAR(75) NOT NULL,
SALARY DECIMAL(15,2) NOT NULL,
PRIMARY KEY(EMPID)
);
ALTER TABLE EMPLOYEETB ADD STATUS VARCHAR(10);

ALTER TABLE EMPLOYEETB ADD DEPATMENTID INT;

INSERT INTO EMPLOYEETB (FIRSTNAME,LASTNAME,SALARY,STATUS) VALUES ('XYZ','PQR',30000,'Active');
INSERT INTO EMPLOYEETB (FIRSTNAME,LASTNAME,SALARY,STATUS) VALUES ('LMN','ABC',50000,'InActive');
INSERT INTO EMPLOYEETB (FIRSTNAME,LASTNAME,SALARY,STATUS,DEPATMENTID) VALUES ('PQR','DTR',40000,'InActive',01);
INSERT INTO EMPLOYEETB (FIRSTNAME,LASTNAME,SALARY,STATUS,DEPATMENTID) VALUES ('JNL','NHK',70000,'InActive',03);
UPDATE EMPLOYEETB
SET salary = '30000'
Where EMPLOYEETB = 1 

--INSERT INTO EMPLOYEETB (EMPID,FIRSTNAME,LASTNAME,SALARY,STATUS,DEPATMENTID) VALUES (1,'JNL','NHK',70000,'InActive',03); 

SELECT * FROM EMPLOYEETB;

TRUNCATE TABLE EMPLOYEETB; /*TRUNCATE is DDL COMMAND WHICH WILL DELETE THE DAT FROM ALL THE ROWS IT DOES NOT HAVE WHERE CLAUSE TO DELETE FROM PERTICULAR ROLW*/
SELECT * FROM EMPLOYEETB; /* TO DELET A RECORD FROM PERTICULAR ROW WE DELETE DML COMMAND WITH WHERE CLAUSE*/

DROP TABLE EMPLOYEETB; /* DROPP WIL DELETE DATA FROM THE ROW AS WELL AS COMPLETE STRUCTURE OF THE TABLE*/

SELECT * FROM EMPLOYEETB;

CREATE TABLE DEPARTMENT
(
DEPTID INT PRIMARY KEY,
DEPTNAME VARCHAR(75)NOT NULL,
EMPID INT
);

INSERT INTO DEPARTMENT VALUES (1001,'SALES',01);
INSERT INTO DEPARTMENT VALUES (1002,'FINANCE',02);
INSERT INTO DEPARTMENT VALUES (1003,'INVENTORY',03);

SELECT * FROM DEPARTMENT;
DROP TABLE DEPARTMENT;
create table EMPLOYEETB1
(
EMPID INT IDENTITY(1,1) NOT NULL,
FIRSTNAME VARCHAR(75) NOT NULL,
LASTNAME VARCHAR(75) NOT NULL,
SALARY DECIMAL(15,2) NOT NULL,
PRIMARY KEY(EMPID)
);
SELECT * FROM EMPLOYEETB1;

DROP TABLE EMPLOYEETB1; 

CREATE TABLE DEPARTMENT
(
DEPTID INT PRIMARY KEY,
DEPTNAME VARCHAR(75)NOT NULL,
EMPID INT FOREIGN KEY REFERENCES EMPLOYEETB(EMPID)
);

--ALTER TABLE EMPLYEETB
--ADD  FOREIGN KEY REFERENCES EMPLOYEETB(EMPID);

INSERT INTO DEPARTMENT VALUES (1001,'SALES',01);
INSERT INTO DEPARTMENT VALUES (1002,'FINANCE',02);
INSERT INTO DEPARTMENT VALUES (1003,'INVENTORY',03);

DELETE FROM DEPARTMENT; -- ALL ROWS WILL GET DELETE 

DELETE FROM DEPARTMENT WHERE DEPTNAME='INVENTORY'; -- ONLY INVENOTRY DEPARTMENT GET DELETE

SELECT * FROM DEPARTMENT;

-- SUB QUERY - QUERY INSIDE A QUERY CALLED AS SUB QUERY.  IT IS MADE UP OF FOLLOWING
-- OUTER QUERY - IT WILL GIVE DISPLAY/THE MAIN OPERATION
-- INNER QUERY - IT WILL GIVE OUTPUT

DELETE FROM DEPARTMENT WHERE DEPTID = (SELECT DEPTID FROM DEPARTMENT WHERE DEPTNAME = 'SALES');

CREATE TABLE STUDENT
(
STDID INT PRIMARY KEY,
STDROLLNO INT UNIQUE,
STDNAME VARCHAR(75) NOT NULL,
STDCLASS VARCHAR(10) DEFAULT 'IX',
STDRESULT VARCHAR(10),
CHECK (STDRESULT = 'PASS')
);

INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1001,12,'SHUBHU','PASS');
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1002,13,'NISHU','PASS');
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1004,52,'SAHU','PASS');
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1007,23,'NAMU','PASS');
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1014,42,'YOGU','PASS');
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1011,62,'CHIKU','PASS');
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1011,73,'LAVYA','PASS'); -- Violation of PRIMARY KEY constraint STUDENT__E20645B5A440B0AA'. Cannot insert duplicate key in object 'dbo.STUDENT'. The duplicate key value is (1011).
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1031,52,'GAYU','PASS');--Violation of UNIQUE KEY constraint 'UQ__STUDENT__45863D0BFF74024C'. Cannot insert duplicate key in object 'dbo.STUDENT'. The duplicate key value is (52).
INSERT INTO STUDENT(STDID,STDROLLNO,STDNAME,STDRESULT) VALUES (1031,78,'XYZ','FAIL');--The INSERT statement conflicted with the CHECK constraint "CK__STUDENT__STDRESU__47DBAE45". The conflict occurred in database "Employee", table "dbo.STUDENT", column 'STDRESULT'.
INSERT INTO STUDENT(STDID,STDROLLNO,STDRESULT) VALUES (1321,88,'PASS');--Cannot insert the value NULL into column 'STDNAME', table 'Employee.dbo.STUDENT'; column does not allow nulls. INSERT fails.
SELECT * FROM STUDENT;

CREATE TABLE DEPT
(
DEPTID INT PRIMARY KEY,
DEPTNAME VARCHAR(75) NOT NULL,
SID INT FOREIGN KEY REFERENCES STUDENT(STDID)
);

INSERT INTO DEPT VALUES (10001,'PRIMARY',1001);
INSERT INTO DEPT VALUES (10021,'SECONDARY',1004);
INSERT INTO DEPT VALUES (10101,'HIGHER SECONDARY',1014);
INSERT INTO DEPT VALUES (11001,'JR COLLEGE',1007);
INSERT INTO DEPT VALUES (11011,'JR COLLEGE',1031);--The INSERT statement conflicted with the FOREIGN KEY constraint "FK__DEPT__SID__4AB81AF0". The conflict occurred in database "Employee", table "dbo.STUDENT", column 'STDID'.
SELECT * FROM DEPT;

CREATE TABLE ADDRES
(
HOUSENO INT,
LOCATOION VARCHAR(75),
VILAGE VARCHAR(75),
CITY VARCHAR(75),
PINCODE INT
);
INSERT INTO DEPT VALUES (11011,'JR COLLEGE',1031);--The INSERT statement conflicted with the FOREIGN KEY constraint "FK__DEPT__SID__4AB81AF0". The conflict occurred in database "Employee", table "dbo.STUDENT", column 'STDID'.

ALTER TABLE ADDRES ADD UNIQUE(LOCATOION);
ALTER TABLE ADDRES ADD DEFAULT 'PALSHI' FOR CITY;
ALTER TABLE ADDRES ADD CHECK(PINCODE=410206);

ALTER TABLE ADDRES MODIFY VILAGE VARCHAR(75) NOT NULL;
ALTER TABLE ADDRES ADD PRIMARY KEY (HOUSENO);
